version: "3.7"
services:

  memcached:
    image: docker.io/memcached:1.4.38

  
  mongodb:
    image: docker.io/mongo:3.2.16
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    volumes:
      - /var/edx/data/mongodb:/data/db

  
  mysql:
    image: docker.io/mysql:5.6.36
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - /var/edx/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "a4sQrRUq"
      MYSQL_DATABASE: openedx
      MYSQL_USER: openedx
      MYSQL_PASSWORD: "h61EqXte"

  
  elasticsearch:
    image: docker.io/elasticsearch:1.5.2
    command: ["elasticsearch", "--cluster.name=openedx", "--bootstrap.mlockall=true"]
    volumes:
      - /var/edx/data/elasticsearch:/usr/share/elasticsearch/data
  

  nginx:
    image: docker.io/nginx:1.13
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases: []
    volumes:
      - /var/edx/nginx:/etc/nginx/conf.d/:ro
      - /var/edx/data/openedx:/var/www/openedx:ro
      - /var/edx/data/openedx-media:/var/www/openedx-media:ro


  rabbitmq:
    image: docker.io/rabbitmq:3.6.10-management-alpine
    volumes:
      - /var/edx/data/rabbitmq:/var/lib/rabbitmq

  
  smtp:
    image: mailhog/mailhog:latest
  


  ci-lms:
    image: 949266541515.dkr.ecr.eu-west-1.amazonaws.com/ci-edx-platform:latest
    environment:
      SERVICE_VARIANT: lms
      GUNICORN_WORKERS: 2
      SETTINGS: production
    volumes:
      - /var/edx/config/:/openedx/config/
      - /var/edx/data/openedx-media:/openedx/media


  ci-cms:
    image: 949266541515.dkr.ecr.eu-west-1.amazonaws.com/ci-edx-platform:latest
    environment:
      SERVICE_VARIANT: cms
      GUNICORN_WORKERS: 2
      SETTINGS: production
    volumes:
      - /var/edx/config/:/openedx/config/
      - /var/edx/data/openedx-media:/openedx/media


  lms-worker:
    image: 949266541515.dkr.ecr.eu-west-1.amazonaws.com/ci-edx-platform:latest
    environment:
      SERVICE_VARIANT: lms
      SETTINGS: production
      C_FORCE_ROOT: "1"
    command: ./manage.py lms celery worker --loglevel=info --hostname=edx.lms.core.default.%%h --maxtasksperchild 100
    volumes:
      - /var/edx/config/:/openedx/config/
      - /var/edx/data/lms:/openedx/data
      - /var/edx/data/openedx-media:/openedx/media


  cms-worker:
    image: 949266541515.dkr.ecr.eu-west-1.amazonaws.com/ci-edx-platform:latest
    environment:
      SERVICE_VARIANT: cms
      SETTINGS: production
      C_FORCE_ROOT: "1"
    command: ./manage.py cms celery worker --loglevel=info --hostname=edx.cms.core.default.%%h --maxtasksperchild 100
    volumes:
      - /var/edx/config/:/openedx/config/
      - /var/edx/data/lms:/openedx/data
      - /var/edx/data/openedx-media:/openedx/media
